/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        fcPrimary: "#362FD9",
        fcSecondary: "#242121",
        primary: "#2156FA",
        secondary: "#EEF0FF", // #2A2E43;
        white: "#FFFFFF",
        orange: "#FF603E",
        fcOrange2: "#E57200",
        fcOrange3: "#FFF2E5",
        gray: "#707070",
        lightGray: "#BABABA",
        lightBlue: "#0085DC",
        darkAsh: "#474747",
        lightYellow: "#F8CE1C",
        lightGreen: "#02BC43",
        green: "#009A3D",
        darkbg: "#0A0B0A",
        fcDark: "#2A2E43",
        fcBlue: "#3F51B5",
        fcNavy: "#28354D",
        fcNavy2: "#2A2E43",
        fcNavy3: "#010334",
        fcNavy4: "#F6F9FA",
        fcNavy5:"#00235B",
        fcNavy6: "#010334",
        fcWhite: "#FFFFFF",
        fcGray: "#2A2E43CC",
        fcGray2: "#2A2E4399",
        fcGray3: "#F7F7F7", //#EE501426 #E4E4E4
        fcGray4: "#D5D5D5",
        fcGray5: "#2A2E43B3",
        fcGray6: "#F5F6F7",
        fcGray7: "#E4E4E4",
        fcGray8: "#EFEFEF",
        fcYellow: "#F8CE1C",
        fcPurple: "#B502BC",
        fcwhitee: "#0000000F",
        fcyellow: "#F8CE1C",
        fcyellow2: "#00C853",
        fcred: "#FF603E",
        fcTomato: "#F7F7F7",
        fcTomato2: "#FFE8E9",
        fcLightGreen: "#C4EFD5",
        fcDarkGreen: "#047832",
        fcPrimary2: "#FFFAF8",
        fcPrimary3: "#FFF2EE",
        fcRed2: "#FF1515",
      },
      // backgroundImage: {
      //   'testimonial': "url('/Assets/img/testimonial.jpg')",
    
      // },
      fontFamily: {
        GilroyBlack: "GilroyBlack",
        GilroyBlackItalic: "GilroyBlackItalic",
        GilroyBold: "GilroyBold",
        GilroyBoldItalic: "GilroyBoldItalic",
        GilroyExtraBold: "GilroyExtraBold",
        GilroyExtraBoldItalic: "GilroyExtraBoldItalic",
        GilroyHeavy: "GilroyHeavy",
        GilroyHeavyItalic: "GilroyHeavyItalic",
        GilroyLight: "GilroyLight",
        GilroyLightItalic: "GilroyLightItalic",
        GilroyMedium: "GilroyMedium",
        GilroyMediumItalic: "GilroyMediumItalic",
        GilroyRegular: "GilroyRegular",
        GilroyRegularItalic: "GilroyRegularItalic",
        GilroySemiBold: "GilroySemiBold",
        GilroySemiBoldItalic: "GilroySemiBoldItalic",
        GilroyThin: "GilroyThin",
        GilroyThinItalic: "GilroyThinItalic",
        GilroyUltraLight: "GilroyUltraLight",
        GilroyUltraLightItalic: "GilroyUltraLightItalic",
      },
    },
  },
  plugins: [],
};
